// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzypiqvnllrszaucyped.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16eXBpcXZubGxyc3phdWN5cGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTE5ODgsImV4cCI6MjA3MjQ4Nzk4OH0.wTMzXyImLcE_xPOyA0alYP_EalOZGsaUwfQGOsWuPGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});